maze/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('signup',views.Signup.as_view(),name="signup"),
    path('start',views.game,name="game"),
    path('authenticate/<int:no>/',views.auth,name='auth'),
    path('board',views.board,name="board"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
	clg=models.CharField(max_length=255)
	mob=models.CharField(max_length=255)

class Game(models.Model):
	username=models.CharField(max_length=255)
	email=models.EmailField(max_length=255)
	clg=models.CharField(max_length=255)
	mob=models.CharField(max_length=255)
	q1_ans_on=models.DateTimeField(null=True)
	q2_ans_on=models.DateTimeField(null=True)
	q3_ans_on=models.DateTimeField(null=True)
	q4_ans_on=models.DateTimeField(null=True)
	q5_ans_on=models.DateTimeField(null=True)
	q6_ans_on=models.DateTimeField(null=True)
	q1=models.BooleanField(default=False)
	q2=models.BooleanField(default=False)
	q3=models.BooleanField(default=False)
	q4=models.BooleanField(default=False)
	q5=models.BooleanField(default=False)
	q6=models.BooleanField(default=False)

	def __str__(self):
		return self.username
				

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser

class Ansform(forms.Form):
	ans=forms.CharField(max_length=255)



class Customusercreationform(UserCreationForm):

	class Meta:
		model=CustomUser
		fields = ('username', 'clg','email', 'mob', )

class Customuserchangeform(UserChangeForm):  
	class Meta:	
		model=CustomUser
		fields=('username','clg','email','mob',)



	

users/views.py
from django.shortcuts import render,redirect
#from . forms import SignupForm 
#from django.contrib.auth import login,authenticate
from .forms import Customusercreationform,Ansform
from django.views import generic
from django.urls import reverse_lazy
import datetime
from .models import CustomUser,Game
from django.utils import timezone
from itertools import chain
import string


# Create your views here.

keys=['a','b','c','d','e','f']

fut=datetime.datetime(2019,3,26,20,30)


def compare(s1, s2):

	s1=s1.replace(" ","")
	s1=s1.replace(".","")


	s2=s2.replace(" ","")
	s2=s2.replace(".","")
	return s1==s2

    



def board(request):
	g6=Game.objects.filter(q6=True).values_list('username', flat=True).order_by('q6_ans_on')
	g5=Game.objects.filter(q5=True,q6=False).values_list('username', flat=True).order_by('q5_ans_on')
	g4=Game.objects.filter(q4=True,q5=False).values_list('username', flat=True).order_by('q4_ans_on')
	g3=Game.objects.filter(q3=True,q4=False).values_list('username', flat=True).order_by('q3_ans_on')
	g2=Game.objects.filter(q2=True,q3=False).values_list('username', flat=True).order_by('q2_ans_on')
	g1=Game.objects.filter(q1=True,q2=False).values_list('username', flat=True).order_by('q1_ans_on')

	res=list(chain(g6,g5,g4,g3,g2,g1))
	context={
	# 'res':list(g6)+g5+g4+g3+g2+g1
	'res':res,

	}

	print(res)
	return render(request,'board.html',context)









def auth(request,no):
	qstn_no=no
	msg="Oops! Try again"

	print(request.user,'name')
	user=CustomUser.objects.get(username=request.user) 
	# print(user.mob) 

	game_obj=Game.objects.filter(username=user.username)
	print(len(game_obj),'length')
	
	if request.method=="POST":
		form=Ansform(request.POST)
		if(form.is_valid()):
			ans=form.cleaned_data['ans']
			print(ans)

			if(len(game_obj)==0):
				print("loop")
				if( compare(ans.lower(),keys[no-1].lower()) ):
					msg="bla"
					print('correct',no)
					try:
						Game.objects.create(username=user.username,email=user.email,clg=user.clg,mob=user.mob,q1_ans_on=timezone.now(),q1=True)
						print("object created")
					except Exception as e:
						print(e)
					qstn_no=2
			
					
							

			else : 
				if( compare(ans.lower(),keys[no-1].lower())):
					msg="bla"
					print('correct',no)
					game_obj=game_obj[0]
					print(game_obj.q2)

					
					try:

						

						if(not game_obj.q2 and no==2): 
				
							game_obj.q2=True
							game_obj.q2_ans_on=timezone.now()
							game_obj.save()
							print("object value added 2")
							

						elif(not game_obj.q3 and no==3): 
				
							game_obj.q3=True
							game_obj.q3_ans_on=timezone.now()
							game_obj.save()
							print("object value added 3")


						elif(not game_obj.q4 and no==4): 
				
							game_obj.q4=True
							game_obj.q4_ans_on=timezone.now()
							game_obj.save()
							print("object value added 4")

						elif(not game_obj.q5 and no==5): 
				
							game_obj.q5=True
							game_obj.q5_ans_on=timezone.now()
							game_obj.save()
							print("object value added 5")
					

						elif(not game_obj.q6 and no==6): 
				
							game_obj.q6=True
							game_obj.q6_ans_on=timezone.now()
							game_obj.save()
							print("object value added 6")			
							




					except Exception as e:
						print(e)
					
					qstn_no=no+1 
					if(qstn_no==7):

						return render(request,'winner.html',{'u':user.username})


					
								


			

			form=Ansform()	

			return render(request,'game.html',{'form':form,'qstn_no':qstn_no,'msg':msg})	


	return redirect('home')		

	# print(no,ans,'last')

def game(request):

	prop="hide"
	pre=datetime.datetime.now()
	#pre=pre.replace(tzinfo=datetime.timezone(datetime.timedelta(0, 19800))).isoformat()

	dif=fut-pre
	print(pre,fut,dif.days)
	if dif.days <0 :
		prop="show"
	print(prop,"game")

	qstn_no=1

	if(request.user.is_authenticated): 
		if prop=="show": 

			user=CustomUser.objects.get(username=request.user)
			game_obj=Game.objects.filter(username=user.username)


			if(len(game_obj)!=0): 
				game_obj=game_obj[0]
				if(not game_obj.q2 ): 
					qstn_no=2
					

				elif(not game_obj.q3): 
					qstn_no=3
		
					


				elif(not game_obj.q4 ): 
					qstn_no=4
		
					
				elif(not game_obj.q5 ): 
					qstn_no=5
		
				elif(not game_obj.q6 ): 
					qstn_no=6
		
				




			form=Ansform()
			return render(request,'game.html',{'form':form,'qstn_no':qstn_no})
	
			
		else : 
			return render(request,'home.html',{'prop':prop})	
			
	else:
		return redirect('login')


	
class Signup(generic.CreateView):
	form_class=Customusercreationform
	success_url=reverse_lazy('login')
	template_name='signup.html'

	


def home(request):
	prop="hide"
	pre=datetime.datetime.now()
	#pre=pre.replace(tzinfo=datetime.timezone(datetime.timedelta(0, 19800))).isoformat()

	dif=fut-pre
	print(pre,fut,dif.days)
	if dif.days <0 :
		prop="show"
	print(prop)	
	return render(request,'home.html',{'prop':prop})

# def signup(request):
# 	if request.method == "POST":
# 		form=SignupForm(request.POST)
# 		p1=request.POST["password1"]
# 		p2=request.POST["password2"]
# 		print(p1,'|'*5,p2)
# 		msg="bla"

# 		if p1 != p2:
# 			msg="Passwords didn't match!!!"
# 		else : 
# 			msg="Password conditions not met!!!"
			

# 		try:
# 			if(form.is_valid):
# 			 form.save()
# 			 username=form.cleaned_data.get("username")
# 			 raw_pass=form.cleaned_data.get("password1")
# 			 user=authenticate(username=username,password=raw_pass)
# 			 login(request,user)
# 			 return redirect('home')
			
# 		except Exception as e:
# 			return render(request,'signup.html',{"signup":form,'msg':msg})
			
# 	else: 
# 		form=SignupForm()
# 	return render(request,'signup.html',{"signup":form})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>maze hunter</title>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/favi.png" />



  <!-- Bootstrap core CSS -->
  <link href="/assets/home/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/assets/home/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="/assets/home/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="/assets/home/css/freelancer.min.css" rel="stylesheet">


</head>

<body id="page-top">
  {% block loader %}
 


{% endblock loader %}





  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">




{% if user.is_authenticated %}

          <li class="nav-item mx-0 mx-lg-1">
          <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="javascript:void(0)"  id="user_name">Hi {{ user.username }}</a> 
         </li>

            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'logout' %}">Logout</a>
          </li>


{% else %}
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'login' %}">Login</a>
          </li>

{% endif %}




        


{% block headersel %}
  
{% endblock headersel %}
          
         

        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->

  {% block mainrep %}
    









  {% endblock %}

  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">

        <div class="col-md-4 mb-5 mb-lg-0">
          
        </div>

      
       

        <div class="col-md-4 mb-5 mb-lg-0">
         <a href="http://sanskritimace.com/" class="sans" style="color: white;"><h4 class="text-uppercase mb-4">sanskriti</h4></a> 
          <ul class="list-inline mb-0">
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://www.facebook.com/sanskritimace/">
                <i class="fab fa-fw fa-facebook-f"></i>
              </a>
            </li>

            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://www.instagram.com/sanskriti.mace/">
                <i class="fab fa-fw fa-instagram"></i>
              </a>
            </li>

         <!--   <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">

                <i class="fab fa-fw  fa-youtube"></i>

              </a>
            </li>-->



          </ul>
        </div>


      </div>
    </div>
  </footer>
<style type="text/css">
  
  a#namegit:hover{
    color: #ff0066;
    text-decoration: none;

  }

</style>
  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Designed &amp; Developed by <a id="namegit" href="https://github.com/ask1234560"> Ananthu.</a></small>
    </div>
  </div>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>


  <!-- Bootstrap core JavaScript -->
  <script src="/assets/home/vendor/jquery/jquery.min.js"></script>
  <script src="/assets/home/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="/assets/home/vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="/assets/home/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="/assets/home/js/jqBootstrapValidation.js"></script>

  <!-- <script src="/assets/home/js/contact_me.js"></script> -->

  <!-- Custom scripts for this template -->
  <script src="/assets/home/js/freelancer.min.js"></script>


</div>

</body>

</html>

templates/board.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

  {% block mainrep %}
    


 
<br>

  <!-- Board -->
<section id="signup">
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-0">board</h2>
    <hr class="star-dark mb-5">
    <div class="row">
      <div class="container">

<table class="table table-hover">

  <thead class="thead-dark">
    <tr>
      <th scope="col">Rankings</th>
      <th scope="col">Usernames</th>
    
    </tr>
  </thead>


  <tbody>

 {% if res %}

    {% for name  in res  %}

  <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{name}}</td>
  </tr>
  
  {% endfor %}
      
 {% else %}

 <tr>
  <th colspan="2">No data yet!!!</th>

 </tr>


      
 {% endif %}



    


    
  </tbody>
</table>




      
    </div>
    </div>
  </div>
</section>

 {% endblock %}

templates/game.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

  {% block mainrep %}
    


 
<br>

  <!-- Game -->
<section id="signup">
 <div class="container">
      <h2 class="text-center text-uppercase text-secondary mb-0">{{qstn_no}}</h2>
      <hr class="star-dark mb-5">
      {% if msg != "bla" %}

   <p id="error" class="text-danger" style="font-size:1.5rem;">{{msg}}</p>
        
      {% endif %}
      
      <hr>
      <div class="row">

 		<div class="col-md-4 mb-5 mb-lg-0">
 			<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
 			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
 			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
 			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
 			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
 			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> -->

      <img src="/assets/puzzle/{{qstn_no}}a.jpeg" class="img-fluid img-thumbnail">
  
        </div>
        <div class="col-md-4 mb-5 mb-lg-0">
        <!-- 	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> -->
           <img src="/assets/puzzle/{{qstn_no}}b.jpeg" class="img-fluid img-thumbnail">
        </div>
        <div class="col-md-4">
        <!--  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
         quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
         consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
         cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
         proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> -->
          <img src="/assets/puzzle/{{qstn_no}}c.jpeg" class="img-fluid img-thumbnail">
        </div>

     

    </div>       
          
<br>
<div id="bottom-ele">
     <form method="POST" action="{% url 'auth' qstn_no %}">
      {% csrf_token %}

        <div class="form-group">
          <!--
          <label for="exampleInputPassword1">Answers</label>
         -->
          {{ form.ans}}
        </div>

        <input type="submit" value="Submit" class="btn btn-secondary btn-sm">

        </form> 

</div>



    </div>
  </section>
<script type="text/javascript">
  
  window.onload =function () {

var inp=$('#id_ans');
inp.addClass('form-control');
inp.attr("placeholder",'Answers');

$(error).fadeOut(8000);
// $(error).hide(10000);
 
  };



</script>






  {% endblock %}

templates/home.html
{% extends "base.html" %}


{% block loader %}

 <script src="/assets/home/vendor/jquery/jquery.min.js" ></script>
<link rel="stylesheet" type="text/css" href="/assets/loader.css">

<script type="text/javascript">
 

$(window).on("load",function() {

 
    // Animate loader off screen
  $('#loader').fadeOut("slow",function(){
    $('#pagetop').fadeIn("medium");

  });




});
 

</script>

  <div id="loader">

<section class="wrapper">
  <div class="spinner">
    <i></i>
    <i></i>
    <i></i>
    <i></i>
    <i></i>
    <i></i>
    <i></i>
  </div>
</section>

</div>
  
  <div id="pagetop" style="display:none;">

{% endblock loader %}



{% block headersel %}




<li class="nav-item mx-0 mx-lg-1" id="play" >
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'game' %}">Play</a>
          </li>

          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'board' %}">Board</a>
          </li>


          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a>
          </li>

  
{% endblock headersel %}



{% block mainrep %}
<script src="/assets/easytimer.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    var timerInstance = new easytimer.Timer();
</script>


<header class="masthead bg-primary text-white text-center">
    <div class="container" id="top">
     <img class="img-fluid mb-5 d-block mx-auto" src="/assets/home/img/profile.png" alt="">
      <h1 class="text-uppercase mb-0">maze hunter</h1>
      <hr class="star-light">

<a class="btn btn-secondary btn-lg " href="{% url 'game' %}" role="button" id="playbtn" >Play</a>
      <div id="countdownExample">

         


  <h2 class="font-weight-light mb-0" id="cusval" style="display: inline-flex;" >


   


    Starts in &nbsp;<div class="values" ></div></h2>

    </div>

    </div>
  </header>


 <!-- About Section -->
  <section class="portfolio" id="about">
    <div class="container">
      <h2 class="text-center text-uppercase text-secondary mb-0">About</h2>


      <hr class="star-dark mb-5">


<div class="row">
  <div class="col-lg-4 ml-auto">
    <p class="lead">
      Prizes worth 5K.
      <br>
      Each correct answer will take you to the next level.
      <br>
      There will be a total of six rounds.

     </p>
  </div>
  <div class="col-lg-4 mr-auto">
    <p class="lead"> The first to reach the end will be the one to walk away with the prize.....
      <br>
    Let the hunt through the maze of music, movies, art and imagination begin........</p>
  </div>
  
</div>
    </div>
  </section>






<!-- Contact Section -->
  <section class="bg-primary text-white mb-0" id="contact">
    <div class="container">
      <h2 class="text-center text-uppercase text-white">Contact Us</h2>
      <hr class="star-light mb-5">
      <div class="row"  >


         
<div class="ml-auto">
    
   
  <li class="list-inline-item">
    <p class="lead">Ananthu</p>
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://api.WhatsApp.com/send?phone=918139811445">
                <i class="fab fa-fw fa-whatsapp"></i>
              </a>
            </li>

  </div>
  <hr>

  <div class="mr-auto">
    
     <li class="list-inline-item">
      <p class="lead">Lynn</p>
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://api.WhatsApp.com/send?phone=917558910696">
                <i class="fab fa-fw fa-whatsapp"></i>
              </a>
            </li>

  </div>




      </div>

   
    </div>
  </section>


<script type="text/javascript">

var play=$('#play');
var playbtn=$('#playbtn');
var count=$('#countdownExample');

{% if prop == "hide" %}

play.hide();
playbtn.hide();


  
{% else %}
count.hide();
play.show('slow');
playbtn.show('slow');

  
{% endif %}



</script>


<script type="text/javascript">

  var fut=new Date(2019,2,26,20,30).getTime();
  var pre=new Date().getTime();
  var dif=fut-pre;

  var sec = dif / 1000;



  var d = Math.floor(sec / (3600*24));


  var h = Math.floor(sec % (3600*24) / 3600);
  var m = Math.floor(sec % 3600 / 60);
  var s = Math.floor(sec % 3600 % 60);


  // var sec = Math.abs(sec);

  var timer = new easytimer.Timer();

timer.start({countdown: true, startValues: {hours:h,minutes:m,seconds: s}});



$('#countdownExample .values').html(d+'d '+timer.getTimeValues().toString());
timer.addEventListener('secondsUpdated', function (e) {
    
    $('#countdownExample .values').html(d+'d '+timer.getTimeValues().toString());
});
timer.addEventListener('targetAchieved', function (e) {

count.hide('medium');
  setTimeout(function(){ window.location.reload(); }, 1000);




    // $('#countdownExample .values').html('KABOOM!!');
});

</script>

  {% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}




{% block mainrep %}


 
<br>

  <!-- Signup -->
<section id="signup">
    <div class="container">
      <h2 class="text-center text-uppercase text-secondary mb-0">Signup</h2>
      <hr class="star-dark mb-5">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
          <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
           <form  id="contactForm"  method="post">

             {% csrf_token %}

             
{{form.as_p}}
<br>
 <div class="form-group">
              <input type="submit" class="btn btn-primary btn-xl" value="Signup" id="signupbtn">
             
            </div>
          </form>
        </div>

      </div>
    </div>
  </section>

<script type="text/javascript">

window.onload=function () {

var ul=$('form ul');
ul.addClass('list-group list-group-flush');

var li=ul.find('li');
li.addClass('list-group-item list-group-item-light');

//li.addClass('text-secondary');


var span=$('form span');
span.addClass('text-info');


var a1=$("#id_username");
  a1.addClass('form-control');
  a1.attr('placeholder','Username');

var a2=$("#id_password1");
  a2.addClass('form-control');
  a2.attr('placeholder','Password');

  var a3=$("#id_clg");
  a3.addClass('form-control');
  a3.attr('placeholder','College');

  var a4=$("#id_password2");
  a4.addClass('form-control');
  a4.attr('placeholder','Confirm Password');

  var a5=$("#id_mob");
  a5.addClass('form-control');
  a5.attr('placeholder','Mob');


  var a6=$("#id_email");
  a6.addClass('form-control');
  a6.attr('placeholder','Email');






//   var p1=$("#id_password1");
//   var p2=$("#id_password2");



// p1.keypress(signch);
// p2.keypress(signch);
// var b=$("#signupbtn");

// function signch(){


// console.log(p1[0].value,p2[0].value);

// if (p1[0].value != p2[0].value) {

// b[0].title="Password didn't match";
// b[0].disabled=true;



// }

// else{
// b[0].title="";
// b[0].disabled=false;


// }

// }

};


</script>





  {% endblock %}

templates/winner.html
{% extends "base.html" %}
{% load crispy_forms_tags %}




{% block mainrep %}


 
<br>

  <!-- winner -->
<section id="winner">
    <div class="container">
      <h2 class="text-center text-uppercase text-secondary mb-0">Winner</h2>
      <hr class="star-dark mb-5">
      

      	<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>Thank you {{u}}, for successfully finishing the game.</p>
  <hr>
  <p class="mb-0">The results will be published shortly.</p>
</div>


      	</div>
  </section>

 {% endblock %}